### PR TITLE
Fix wrong use of map of Set for summation

### PR DESCRIPTION
**Pull request by sezruby**
### What is the context for this pull request?

 - **Tracking Issue**: n/a
 - **Parent Issue**: n/a
 - **Dependencies**: n/a

### What changes were proposed in this pull request?

Fix a bug in `IndexLogEntry.sourceFilesSzieInBytes`.
`Set.map(_.size).sum` returns incorrect results.

### Does this PR introduce _any_ user-facing change?

Yes, fixes the bug.

### How was this patch tested?

tested by unit tests in #272

### CODE REVIEW

**Comment by imback82** [comment]
> tested by unit tests in #272

Can we add simple tests in this PR? It's weird that tests are done by a different PR.

**Comment by imback82** [comment]
> `Set.map(_.size).sum` returns incorrect results.

I wasn't aware of this. Could you explain a bit more? `Set(1, 2, 3).map(a => a).sum` seems fine?

**Comment by sezruby** [comment]
`Set(((a,1), (b,1)).map(_._2).sum` returns 1 it's because map result became Set, not Seq..

**Comment by sezruby** [comment]
> Can we add simple tests in this PR? It's weird that tests are done by a different PR.

Not sure this PR needs a separate test..

**Comment by imback82** [comment]
> Not sure this PR needs a separate test..

How did you verify the fix then?

**Comment by sezruby** [comment]
@imback82 Updated a simple test. Thanks!

**Review by imback82 — APPROVED** [review]
LGTM, thanks @sezruby!

**Comment by imback82** [comment]
> `Set(((a,1), (b,1)).map(_._2).sum` returns 1 it's because map result became Set, not Seq..

👍🏼

**Pull request merged**
