### PR TITLE
Update CONTRIBUTING.md for PR submission guide for a major feature

### PR DESCRIPTION
**Pull request by imback82**
### What changes were proposed in this pull request?

This PR proposes to update `CONTRIBUTING.md` to add PR submission guide when a contributor works on a major feature.

### CODE REVIEW

**Comment by imback82** [comment]
cc @rapoth @sezruby @andrei-ionescu

**Comment by sezruby** [comment]
LGTM + it would be good to mention that it won't be a problem to merge PRs one by one though each sub-task PR itself is incomplete.

**Comment by andrei-ionescu** [comment]
I'm ok with it as it is. Thanks!

**Review by andrei-ionescu — APPROVED** [review]

**Comment by imback82** [comment]
Thanks @sezruby / @andrei-ionescu for the review, merging to master! (@sezruby feel free to create a PR if the current version is not clear enough).

**Pull request merged**
