### PR TITLE
[PROPOSAL] Introduce Bloom Filter Index

### PR DESCRIPTION
**Pull request by sezruby**
### What is the context for this pull request?

 - **Tracking Issue**: #161 
 - **Parent Issue**: N/A
 - **Dependencies**: N/A
   - Issue 1
   - Issue 2

### What changes were proposed in this pull request?

A draft design document for #161 

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Intellij markdown util

### CODE REVIEW

**Comment by sezruby** [comment]
@imback82 Can we merge this PR? So that @thugsatbay could update the document.

**Comment by imback82** [comment]
@rapoth What's the plan for proposals moving forward? Are we checking in as a doc or have it as an issue similar to #263?

**Comment by imback82** [comment]
Another way is to create a "Proposal" category under Discussions.

**Comment by imback82** [comment]
In summary, we can pick one of the three to write a proposal:
1) Check in as a doc: current PR
2) Create as an issue and label is as "proposal": #263 
3) Create a proposal under Discussions.

@rapoth @sezruby @pirz @apoorvedave1 @thugsatbay WDYT?

**Comment by imback82** [comment]
My vote is `2)` since `1)` doesn't seem to be going well: check https://github.com/microsoft/hyperspace/tree/master/docs/design. Since design docs can/need to be iterated quite a few times, requiring a check in to the repo doesn't seem like a good idea for productivity.

**Comment by rapoth** [comment]
I agree. It looks like we're having more luck with writing proposals as Issues. The second form was only meant for very large items but we might as well evolve the template inside Issues itself. The only rationale behind a check-in was to encourage PR reviews (a.k.a. Design reviews) but let's do whatever scales for the community.

I am neutral as far as using _Disussions_ is concerned. There is a category _Idea_ that @thugsatbay pointed me to yesterday that we could use for initial discussions (before proposals are written). It looks like we can create a new category as well that we could leverage for _Proposals_.  However, do note that since discussions are not conventional issues, they do not show up in our planning system so it might be hard to incorporate planning. Therefore, unless someone strongly objects, we could have initial ideas as discussions but Proposals should remain as issues.

**Comment by sezruby** [comment]
Yep 2) would be good as it's easy to edit & track.

**Comment by pirz** [comment]
Using (2) is Ok as long as people do check them there. The main issue is that adding an item under issues which is really a design doc and needs interactive comment/reply does not fit with the "issues" category. What if we have separate category just for design proposals? Is that doable in Github?

**Comment by thugsatbay** [comment]
Even if we end up discussing on `Discussion platform` on Github we would end up creating an # Issue for tracking for planning which will just make the flow ugly. So I guess I feel option 2 is good enough. By adding correct/differentiating labels while creating # Issues for proposal and design docs we can do a quick filter that allows us to categorize our content and should work for what @pirz asked in his last question ?!.

**Pull request closed without merging**
