### PR TITLE
Build on Windows (sanity check)

### PR DESCRIPTION
**Pull request by imback82**
### What is the context for this pull request?

TBD

### What changes were proposed in this pull request?

TBD

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

TBD

### CODE REVIEW

**Comment by imback82** [comment]
I see failures from the following:
```
[error] Failed tests:
[error] 	com.microsoft.hyperspace.index.HybridScanForIcebergTest
[error] 	com.microsoft.hyperspace.index.IcebergIntegrationTest

```
, mostly due to
```

[info]   at org.apache.iceberg.spark.source.CustomCatalogs.loadCatalog(CustomCatalogs.java:65)
[info]   ...
[info]   Cause: java.lang.NoSuchMethodException: Cannot find constructor for interface org.apache.iceberg.catalog.Catalog
[info] 	Missing org.apache.iceberg.hive.HiveCatalog [java.lang.NoClassDefFoundError: org/apache/hadoop/hive/metastore/api/NoSuchObjectException]
[info]   at org.apache.iceberg.common.DynConstructors$Builder.buildChecked(DynConstructors.java:227)
[info]   at org.apache.iceberg.CatalogUtil.loadCatalog(CatalogUtil.java:155)
[info]   at org.apache.iceberg.CatalogUtil.buildIcebergCatalog(CatalogUtil.java:194)
[info]   at org.apache.iceberg.spark.source.CustomCatalogs.buildCatalog(CustomCatalogs.java:85)
[info]   at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2337)
[info]   at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
[info]   at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2335)
[info]   at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2318)
[info]   at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:111)
[info]   at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:54)
[info]   ...

```

I haven't investigated the root cause yet. @sezruby, which test was failing for #375?

**Comment by sezruby** [comment]
Yea #375 will fix both tests.

**Comment by imback82** [comment]
Thanks, looks like I need to add `hive` package to resolve the catalog error above. I will merge this once #375 is in.

**Comment by andrei-ionescu** [comment]
Good thing to have a Windows OS build step.

**Comment by imback82** [comment]
@apoorvedave1 The following test is failing on Windows. Could you check when you get a chance?

```
[info] TPCDSV1_4_SparkPlanStabilitySuite:
[info] - check simplified (tpcds-v1.4/q1) *** FAILED ***
```

**Comment by clee704** [comment]
Cleaning up old PRs. AFAIK Windows build has no problem now.

**Comment by imback82** [comment]
Reopening. We need to update azure-pipeline to build on Windows. Otherwise, we will never know when we introduce a change that breaks builds on Windows.

Also, please kindly ping the author before closing a PR.

**Comment by imback82** [comment]
I create #469 to better track this.

**Comment by clee704** [comment]
> Reopening. We need to update azure-pipeline to build on Windows. Otherwise, we will never know when we introduce a change that breaks builds on Windows.
> 
> Also, please kindly ping the author before closing a PR that is not yours.

Sorry, but maybe closing is the best kind of pinging. You get the notification (if you don't, well, no point in leaving a comment first because you'll miss it too) and you can reopen it anyway... But I'll be more clear on my wording next time 😅

**Comment by clee704** [comment]
BTW, if you are not going to work on this, shouldn't we close this PR? It'll still be visible in the linked issue should anyone need a reference.

**Comment by imback82** [comment]
I'll update this PR if no one picks this up in a couple of weeks.

**Comment by paryoja** [comment]
Let me see the issues.

**Comment by imback82** [comment]
#470 will replace this.

**Pull request closed without merging**
